const NAMESPACE = 'GITHUB';

const actions = {
  user: {
    FETCH_ALL: `${NAMESPACE}_USER_FETCH_ALL`,
    FETCH_ALL_SUCCESS: `${NAMESPACE}_USER_FETCH_ALL_SUCCESS`,
    FETCH_ALL_ERROR: `${NAMESPACE}_USER_FETCH_ALL_ERROR`,
    FETCH_BY_USERNAME: `${NAMESPACE}_USER_FETCH_BY_USERNAME`,
    FETCH_BY_USERNAME_SUCCESS: `${NAMESPACE}_USER_FETCH_BY_USERNAME_SUCCESS`,
    FETCH_BY_USERNAME_ERROR: `${NAMESPACE}_USER_FETCH_BY_USERNAME_ERROR`
  },
  repo: {
    FETCH_BY_USERNAME: `${NAMESPACE}_REPO_FETCH_BY_USERNAME`,
    FETCH_BY_USERNAME_SUCCESS: `${NAMESPACE}_REPO_FETCH_BY_USERNAME_SUCCESS`,
    FETCH_BY_USERNAME_ERROR: `${NAMESPACE}_REPO_FETCH_BY_USERNAME_ERROR`,
  }
};

export default actions;